baseURL = 'https://tunamoon.github.io/hugo-mock-landing-page-autodeployed/'
title = "every now & then"
author = "Luna Chen"
copyright = "Luna Chen 2026"

timeZone = 'Europe/London'

# Multilingual
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

theme = "hugo-bootstrap-theme"
themesdir = 'node_modules/@filipecarneiro'

disableHugoGeneratorInject = true
enableRobotsTXT = true
#enableGitInfo = true
enableEmoji = true
#sectionPagesMenu = "main"
#googleAnalytics = "UA-1511XXXX-X"
  weight = 90
  
[[menu.main]]
  name = "Instagram"
  pre = "<img src='/images/instagram.svg' width='30' height='30' alt='Instagram'>"
  url = "https://www.instagram.com/everynowthenn"
  weight = 90


[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":fileModTime", ":default"]

[taxonomies]
  tag = "tags"
  category = "categories"
  series = 'series'
  author = "authors"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
#  post = "/post/:title/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
